Repository Staffbase/autodev-action, pull requests merged in 2022-05, with the labels that each got.

#55 :arrow_up: Manual Dependabot PR
  .github/workflows/release.yaml
  .nvmrc
  README.md
  action.yml
  package-lock.json
  package.json
Labels: dependencies

#36 handle empty strings in custom comments
  README.md
  __test__/autodev.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/autodev.ts
  src/utils.ts
Labels: bug

#60 🎨 Update comments
  dist/index.js
  dist/index.js.map
  src/autodev.ts
  src/utils.ts
Labels: enhancement

#61 Improve readme
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-dist.yml
  .github/workflows/cla.yml
  .github/workflows/integration.yml
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/autodev.ts
Labels: documentation

#66 :art: increase page limit
  README.md
  src/utils.ts
Labels: bug
